const fs = require('fs');

const indexContent = fs.readFileSync('index.html', 'utf8');
const headerParts = indexContent.split('<!-- Hero Section -->');
const topLayout = headerParts[0];
const footerParts = indexContent.split('<!-- Footer -->');
const bottomLayout = '<!-- Footer -->' + footerParts[1];

const pages = [
  {
    name: 'contact.html',
    title: 'Contact Us | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Contact Us</h1><p>Schedule your consultation with our experienced legal team.</p></div></section><section class="section"><div class="container grid grid-cols-2" style="align-items: start;"><div><h2 class="text-navy">Get In Touch</h2><div class="divider" style="margin: 1rem 0;"></div><p class="mt-3 mb-5">Fill out the form below to request a consultation. Our team will get back to you promptly to discuss your legal needs.</p><ul class="contact-info-footer" style="font-size: 1.1rem;"><li class="mb-3"><i class="fa-solid fa-envelope text-gold"></i> <a href="mailto:clevengerkenneth3@gmail.com" class="text-navy">clevengerkenneth3@gmail.com</a></li><li class="mb-3"><i class="fa-solid fa-phone text-gold"></i> <a href="tel:+12053776372" class="text-navy">International: +1 (205) 377-6372</a></li><li class="mb-3"><i class="fa-solid fa-phone text-gold"></i> <a href="tel:+447346507855" class="text-navy">UK Local: +44 7346 507855</a></li><li class="mb-3"><i class="fa-solid fa-location-dot text-gold"></i> 79 Jedburgh Road<br>LERWICK<br>ZE1 8HQ</li></ul></div><div class="bg-light" style="padding: 3rem; border-radius: 4px;"><form id="contactForm"><div class="form-group"><label>Full Name</label><input type="text" class="form-control" id="formName" placeholder="Your Name" required></div><div class="form-group"><label>Email Address</label><input type="email" class="form-control" id="formEmail" placeholder="Your Email" required></div><div class="form-group"><label>Phone Number</label><input type="tel" class="form-control" id="formPhone" placeholder="Your Phone Number"></div><div class="form-group"><label>Message / Case Details</label><textarea class="form-control" id="formBody" rows="5" placeholder="Briefly describe your legal needs..." required></textarea></div><button type="submit" class="btn btn-primary" style="width: 100%;">Send Consultation Request</button><p class="mt-3" style="font-size: 0.8rem; color: #666;">Note: This will open your email client to send the request securely.</p></form></div></div></section><script>document.getElementById("contactForm").addEventListener("submit", function(e) { e.preventDefault(); const name = document.getElementById("formName").value; const email = document.getElementById("formEmail").value; const phone = document.getElementById("formPhone").value; const body = document.getElementById("formBody").value; const fullMessage = "Name: " + name + "\\nEmail: " + email + "\\nPhone: " + phone + "\\n\\nMessage:\\n" + body; window.location.href = "mailto:clevengerkenneth3@gmail.com?subject=Consultation Request from " + encodeURIComponent(name) + "&body=" + encodeURIComponent(fullMessage); });</script>'
  },
  {
    name: 'faq.html',
    title: 'Frequently Asked Questions | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Frequently Asked Questions</h1><p>Clear answers to common legal inquiries.</p></div></section><section class="section bg-light"><div class="container" style="max-width: 800px;"><h2 class="text-center text-navy mb-5">General Information</h2><details class="faq-item" open><summary>What should I bring to my initial consultation?</summary><div class="faq-content">Please bring any documents relevant to your case, including contracts, correspondence, court notices, financial records, and a timeline of events. Having these prepared allows our attorneys to provide a more accurate preliminary assessment.</div></details><details class="faq-item"><summary>How does the firm charge for its services?</summary><div class="faq-content">Our billing structure depends on the nature of your case. We offer hourly rates for corporate counsel and complex litigation, flat fees for specific transactional work like estate planning, and contingency fees for select civil litigation cases. We will discuss all costs transparently during your initial consultation.</div></details><details class="faq-item"><summary>Will my case go to trial?</summary><div class="faq-content">Not necessarily. The vast majority of civil and corporate disputes are settled out of court through negotiation or mediation. However, our attorneys are seasoned trial lawyers. If a fair settlement cannot be reached, we are fully prepared to fiercely advocate for you in the courtroom.</div></details><details class="faq-item"><summary>How long will my legal matter take to resolve?</summary><div class="faq-content">The timeline varies significantly depending on the complexity of the case, the cooperation of the opposing party, and court schedules. Simple matters may resolve in weeks, while complex litigation can take years. We prioritize efficient resolutions while never compromising on securing the best possible outcome.</div></details><details class="faq-item"><summary>Who will actually be working on my case?</summary><div class="faq-content">You will be assigned a lead attorney based on their specific expertise in your required practice area. They may be supported by associates and paralegals to ensure cost-efficiency, but your lead attorney will always oversee the strategy and remain your primary point of contact.</div></details></div></section>'
  },
  {
    name: 'news.html',
    title: 'Live Legal News | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Global Legal News & Court Cases</h1><p>Live updates on court cases and legal affairs around the world.</p></div></section><section class="section bg-light"><div class="container"><div id="news-loading" class="text-center"><i class="fa-solid fa-circle-notch fa-spin text-gold" style="font-size: 3rem;"></i><p class="mt-3">Fetching live updates...</p></div><div id="news-container" class="grid grid-cols-3" style="display: none;"><!-- JS injects here --></div><div id="news-error" class="text-center" style="display: none;"><p class="text-navy">Failed to load news. Please try again later.</p></div></div></section><script>const NEWS_API_URL = "https://api.rss2json.com/v1/api.json?rss_url=https://www.jurist.org/news/feed/"; fetch(NEWS_API_URL).then(response => response.json()).then(data => { document.getElementById("news-loading").style.display = "none"; const container = document.getElementById("news-container"); container.style.display = "grid"; if(data && data.items) { data.items.slice(0, 9).forEach(item => { const date = new Date(item.pubDate).toLocaleDateString(); container.innerHTML += "<div class=\\"feature-card\\"><h3 style=\\"font-size: 1.1rem; margin-bottom: 0.5rem;\\"><a href=\\"" + item.link + "\\" target=\\"_blank\\">" + item.title + "</a></h3><p style=\\"font-size: 0.85rem; color: #666; margin-bottom: 1rem;\\">" + date + "</p><p style=\\"font-size: 0.95rem;\\">" + item.description.replace(/<[^>]*>?/gm, "").substring(0, 120) + "...</p><a href=\\"" + item.link + "\\" target=\\"_blank\\" class=\\"learn-more\\">Read Full Article <i class=\\"fa-solid fa-chevron-right\\"></i></a></div>"; }); } else { throw new Error("No items"); } }).catch(error => { console.error("Error fetching news:", error); document.getElementById("news-loading").style.display = "none"; document.getElementById("news-error").style.display = "block"; });</script>'
  },
  {
    name: 'about.html',
    title: 'About Us | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">About Our Firm</h1><p>Excellence, Integrity, and Results.</p></div></section><section class="section"><div class="container"><div class="grid grid-cols-2" style="gap: 4rem; align-items: center;"><div><h2 class="text-navy">A Legacy of Legal Excellence</h2><div class="divider" style="margin: 1rem 0 2rem 0;"></div><p class="mb-3">Clevenger Kenneth Law Firm has been a pillar of the legal community for over 25 years. We pride ourselves on delivering top-tier legal counsel to individuals, families, and global corporations.</p><p class="mb-3">Our mission is simple: to provide unwavering advocacy, maintain the highest ethical standards, and secure the best possible outcomes for our clients through strategic, innovative legal solutions.</p><h3 class="mt-5 text-gold" style="font-size: 1.5rem;">Our Core Values</h3><ul style="list-style-type: disc; margin-left: 1.5rem;" class="mt-3"><li class="mb-2"><strong>Integrity:</strong> Honest and transparent communication at every step.</li><li class="mb-2"><strong>Excellence:</strong> Relentless pursuit of perfection in legal strategy.</li><li class="mb-2"><strong>Client-Centric:</strong> Your priorities are our driving force.</li><li class="mb-2"><strong>Innovation:</strong> Adapting to a rapidly changing legal landscape.</li></ul></div><div class="placeholder-img" style="height: 500px; background-image: url(\'group.jpg\'); background-size: contain; background-repeat: no-repeat; background-position: center; background-color: var(--light-gray);"></div></div></div></section>'
  },
  {
    name: 'attorneys.html',
    title: 'Attorneys | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Our Legal Team</h1><p>World-class attorneys dedicated to your success.</p></div></section><section class="section bg-light"><div class="container"><h2 class="text-center text-navy mb-5">Meet Our Attorneys</h2><div class="grid grid-cols-2" style="gap: 2rem;"><div style="background: white; border-radius: 4px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); overflow: hidden;"><div class="attorney-img" style="height: 350px; background-image: url(\'clevenger.jpg\'); background-size: contain; background-repeat: no-repeat; background-position: center; background-color: var(--light-gray);"></div><div style="padding: 2rem;"><h3 class="text-navy">Clevenger Kenneth</h3><h5 class="text-gold mb-3">Senior Managing Partner</h5><p class="mb-3">Expert in high-stakes corporate litigation and complex family law cases.</p></div></div><div style="background: white; border-radius: 4px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); overflow: hidden;"><div class="attorney-img" style="height: 350px; background-image: url(\'isabella.jpg\'); background-size: contain; background-repeat: no-repeat; background-position: center; background-color: var(--light-gray);"></div><div style="padding: 2rem;"><h3 class="text-navy">Isabella MacLeod</h3><h5 class="text-gold mb-3">Partner - Real Estate & Estate Planning</h5><p class="mb-3">Over 15 years of experience in commercial real estate transactions and wealth preservation.</p></div></div><div style="background: white; border-radius: 4px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); overflow: hidden;"><div class="attorney-img" style="height: 350px; background-image: url(\'declan.jpg\'); background-size: contain; background-repeat: no-repeat; background-position: center; background-color: var(--light-gray);"></div><div style="padding: 2rem;"><h3 class="text-navy">Declan O\'Connor</h3><h5 class="text-gold mb-3">Senior Associate - Business Law</h5><p class="mb-3">Specializes in mergers, acquisitions, and startup regulatory compliance.</p></div></div><div style="background: white; border-radius: 4px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); overflow: hidden;"><div class="attorney-img" style="height: 350px; background-image: url(\'sophia.jpg\'); background-size: contain; background-repeat: no-repeat; background-position: center; background-color: var(--light-gray);"></div><div style="padding: 2rem;"><h3 class="text-navy">Sophia Davies</h3><h5 class="text-gold mb-3">Associate - Civil Litigation</h5><p class="mb-3">A fierce advocate in the courtroom with a track record of significant civil settlements.</p></div></div></div></div></section>'
  },
  {
    name: 'practice-areas.html',
    title: 'Practice Areas | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Practice Areas</h1><p>Comprehensive legal services across multiple disciplines.</p></div></section><section class="section"><div class="container"><div class="grid grid-cols-3"><div class="practice-card"><i class="fa-solid fa-gavel practice-icon"></i><h3>Civil Litigation</h3><p>We represent plaintiffs and defendants in high-stakes civil disputes, from breach of contract to complex torts, ensuring your rights are fiercely protected in the courtroom.</p></div><div class="practice-card"><i class="fa-solid fa-people-roof practice-icon"></i><h3>Family Law</h3><p>Compassionate and discrete representation in divorce, child custody, alimony, and prenuptial agreements. We navigate emotional disputes with tactical precision.</p></div><div class="practice-card"><i class="fa-solid fa-briefcase practice-icon"></i><h3>Business & Corporate Law</h3><p>Guiding startups and multinational corporations through mergers, acquisitions, regulatory compliance, and corporate structuring.</p></div><div class="practice-card"><i class="fa-solid fa-house-chimney practice-icon"></i><h3>Real Estate Law</h3><p>Expertise in commercial and residential property transactions, zoning laws, leasing agreements, and landlord-tenant disputes.</p></div><div class="practice-card"><i class="fa-solid fa-file-contract practice-icon"></i><h3>Estate Planning</h3><p>Securing your legacy through comprehensive wills, trusts, probate administration, and wealth preservation strategies.</p></div><div class="practice-card"><i class="fa-solid fa-user-shield practice-icon"></i><h3>Employment Law</h3><p>Advocating for employers and employees in cases involving wrongful termination, workplace discrimination, and non-compete agreements.</p></div></div></div></section>'
  },
  {
    name: 'case-results.html',
    title: 'Case Results | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Case Results</h1><p>A track record of significant victories and settlements.</p></div></section><section class="section bg-light"><div class="container"><p class="text-center mb-5"><em>Disclaimer: Past results do not guarantee, warrant, or predict future case outcomes. Each case is strictly evaluated on its own merits.</em></p><div class="grid grid-cols-2"><div class="result-card"><h3 class="text-navy">$12.5 Million Verdict</h3><p class="text-gold mb-2"><strong>Corporate Fraud Litigation</strong></p><p>Successfully represented a group of investors defrauded by a multinational tech conglomerate, securing a massive jury verdict after a 6-week trial.</p></div><div class="result-card"><h3 class="text-navy">Favorable Settlement</h3><p class="text-gold mb-2"><strong>High-Net-Worth Divorce</strong></p><p>Negotiated a highly complex marital dissolution involving offshore assets, multiple international properties, and intricate business valuations.</p></div><div class="result-card"><h3 class="text-navy">$4.1 Million Settlement</h3><p class="text-gold mb-2"><strong>Breach of Contract</strong></p><p>Achieved a pre-trial settlement for a manufacturing client whose supplier fundamentally breached a critical supply chain agreement.</p></div><div class="result-card"><h3 class="text-navy">Full Dismissal</h3><p class="text-gold mb-2"><strong>White-Collar Defense</strong></p><p>Successfully defended a corporate executive against federal embezzlement charges, resulting in a full dismissal of all counts before trial.</p></div></div></div></section>'
  },
  {
    name: 'testimonials.html',
    title: 'Testimonials | Clevenger Kenneth Law Firm',
    content: '<section class="page-header bg-navy text-white"><div class="container"><h1 class="text-gold">Client Testimonials</h1><p>Hear from those we\'ve had the privilege to represent.</p></div></section><section class="section"><div class="container"><div class="grid grid-cols-2"><div class="feature-card"><i class="fa-solid fa-quote-left text-gold mb-3" style="font-size: 2rem;"></i><p class="mb-3" style="font-style: italic; font-size: 1.1rem;">"Professional, responsive, and highly knowledgeable. Clevenger Kenneth guided us through every step of our corporate merger with absolute confidence. Their strategic insight saved us millions."</p><strong>- Michael T., CEO</strong></div><div class="feature-card"><i class="fa-solid fa-quote-left text-gold mb-3" style="font-size: 2rem;"></i><p class="mb-3" style="font-style: italic; font-size: 1.1rem;">"Outstanding communication and attention to detail. Going through a complex divorce is harrowing, but I felt completely protected and supported throughout the entire process."</p><strong>- Sarah W.</strong></div><div class="feature-card"><i class="fa-solid fa-quote-left text-gold mb-3" style="font-size: 2rem;"></i><p class="mb-3" style="font-style: italic; font-size: 1.1rem;">"Excellent legal advice and exceptional professionalism from start to finish. When our real estate deal hit a major regulatory roadblock, this firm untangled it in a matter of weeks."</p><strong>- David L.</strong></div><div class="feature-card"><i class="fa-solid fa-quote-left text-gold mb-3" style="font-size: 2rem;"></i><p class="mb-3" style="font-style: italic; font-size: 1.1rem;">"I was facing severe employment litigation that threatened my career. Clevenger Kenneth provided a defense that was aggressive, tactful, and ultimately victorious. Highly recommended."</p><strong>- Elena R.</strong></div></div></div></section>'
  }
];

pages.forEach(page => {
  const newTop = topLayout.replace(/<title>.*?<\/title>/, "<title>" + page.title + "</title>");
  const html = newTop + '\n' + page.content + '\n' + bottomLayout;
  fs.writeFileSync(page.name, html);
  console.log('Created ' + page.name);
});
